### PR TITLE
Set correct Yola version for the package

### PR DESCRIPTION
**Pull request by RayeN**

### CODE REVIEW

**Comment by RayeN** [comment]
:+1:

**Comment by jamesodo** [comment]
Eugene asked me to click merge for him since github buttons are broken for him.

**Comment by ekoval** [comment]
Yes! Each member of Yola team will be asked to click two buttons a day for me :)

**Comment by stefanor** [comment]
Why do we have a Yola fork of this? Has anyone tried to upstream our changes?

**Comment by RayeN** [comment]
I think the current master of lettuce is perfectly fine for us.  And when it is released - we could use it.  Thus we could probably just remove this fork (anyway our fork doesn't contain any changes comparing to the original code)

**Pull request merged**
